# Generated by Django 5.0.6 on 2026-08-16 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('moving', 'Moving Help'), ('lifting', 'Heavy Lifting'), ('assembly', 'Furniture Assembly'), ('cleaning', 'Cleaning'), ('junk', 'Junk Removal'), ('van', 'Van / Truck Needed'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_needed', models.CharField(max_length=60)),
                ('duration_hrs', models.CharField(blank=True, max_length=40)),
                ('rate_offered', models.CharField(blank=True, max_length=100)),
                ('helpers_needed', models.PositiveSmallIntegerField(default=1)),
                ('poster_name', models.CharField(max_length=120)),
                ('poster_email', models.EmailField(max_length=254)),
                ('poster_phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('management_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=120)),
                ('worker_phone', models.CharField(max_length=40)),
                ('worker_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='helpers.taskrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
