# Generated by Django 5.0.6 on 2026-08-16 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='pay_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed price')], default='hourly', max_length=10),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='poster_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
